package android.taobao.atlas.bundleInfo;

import android.taobao.atlas.bundleInfo.BundleListing;
import com.yunos.tvtaobao.biz.common.BaseConfig;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;

public class AtlasBundleInfoGenerator {
    public static BundleListing generateBundleInfo() {
        LinkedHashMap<String, BundleListing.BundleInfo> bundleInfos = new LinkedHashMap<>();
        BundleListing listing = new BundleListing();
        listing.bundles = bundleInfos;
        BundleListing.BundleInfo info = new BundleListing.BundleInfo();
        HashMap<String, Boolean> activities = new HashMap<>();
        HashMap<String, Boolean> services = new HashMap<>();
        HashMap<String, Boolean> receivers = new HashMap<>();
        HashMap<String, Boolean> providers = new HashMap<>();
        HashMap<String, String> remoteFragments = new HashMap<>();
        HashMap<String, String> remoteViews = new HashMap<>();
        HashMap<String, String> remoteTransactors = new HashMap<>();
        List<String> dependencies = new ArrayList<>();
        info.activities = activities;
        info.services = services;
        info.receivers = receivers;
        info.contentProviders = providers;
        info.remoteFragments = remoteFragments;
        info.remoteViews = remoteViews;
        info.remoteTransactors = remoteTransactors;
        info.dependency = dependencies;
        info.unique_tag = "2u7urnwlmkngs";
        info.pkgName = "com.yunos.tvtaobao.h5.commonbundle";
        info.isInternal = true;
        activities.put(BaseConfig.SWITCH_TO_COMMON_ACTIVITY, Boolean.FALSE);
        activities.put(BaseConfig.SWITCH_TO_RECOMMEND_ACTIVITY, Boolean.FALSE);
        activities.put(BaseConfig.SWITCH_TO_RELATIVERECOMMEND_ACTIVITY, Boolean.FALSE);
        activities.put(BaseConfig.SWITCH_TO_CHAOSHI_ACTIVITY, Boolean.FALSE);
        activities.put(BaseConfig.SWITCH_TO_TODAYGOODS_ACTIVITY, Boolean.FALSE);
        activities.put(BaseConfig.SWITCH_TO_CHONGZHI_ACTIVITY, Boolean.FALSE);
        activities.put(BaseConfig.SWITCH_TO_ORDERLIST_ACTIVITY, Boolean.FALSE);
        activities.put(BaseConfig.SWITCH_TO_POINT_ACTIVITY, Boolean.FALSE);
        activities.put(BaseConfig.SWITCH_TO_SHOP_BLIZ_ACTIVITY, Boolean.FALSE);
        activities.put(BaseConfig.SWITCH_TO_TAKEOUT_WEB_ACTIVITY, Boolean.FALSE);
        activities.put(BaseConfig.SWITCH_TO_ADDRESS_WEB_ACTIVITY, Boolean.FALSE);
        bundleInfos.put(info.pkgName, info);
        BundleListing.BundleInfo info2 = new BundleListing.BundleInfo();
        HashMap<String, Boolean> activities2 = new HashMap<>();
        HashMap<String, Boolean> services2 = new HashMap<>();
        HashMap<String, Boolean> receivers2 = new HashMap<>();
        HashMap<String, Boolean> providers2 = new HashMap<>();
        HashMap<String, String> remoteFragments2 = new HashMap<>();
        HashMap<String, String> remoteViews2 = new HashMap<>();
        HashMap<String, String> remoteTransactors2 = new HashMap<>();
        List<String> dependencies2 = new ArrayList<>();
        info2.activities = activities2;
        info2.services = services2;
        info2.receivers = receivers2;
        info2.contentProviders = providers2;
        info2.remoteFragments = remoteFragments2;
        info2.remoteViews = remoteViews2;
        info2.remoteTransactors = remoteTransactors2;
        info2.dependency = dependencies2;
        info2.unique_tag = "3w4o5k8yq83sk";
        info2.pkgName = "com.yunos.tvtaobao.mytaobao";
        info2.isInternal = true;
        activities2.put(BaseConfig.SWITCH_TO_FOLLOW_ACTIVITY, Boolean.FALSE);
        activities2.put("com.yunos.tvtaobao.mytaobao.activity.MyTaoBaoActivity", Boolean.FALSE);
        activities2.put(BaseConfig.SWITCH_TO_ADDRESS_ACTIVITY, Boolean.FALSE);
        activities2.put(BaseConfig.SWITCH_TO_COUPON_ACTIVITY, Boolean.FALSE);
        activities2.put(BaseConfig.SWITCH_TO_COLLECTS_ACTIVITY, Boolean.FALSE);
        activities2.put("com.yunos.tvtaobao.mytaobao.activity.NewMyTaoBaoActivity", Boolean.FALSE);
        activities2.put(BaseConfig.SWITCH_TO_FOOTMARK_ACTIVITY, Boolean.FALSE);
        bundleInfos.put(info2.pkgName, info2);
        BundleListing.BundleInfo info3 = new BundleListing.BundleInfo();
        HashMap<String, Boolean> activities3 = new HashMap<>();
        HashMap<String, Boolean> services3 = new HashMap<>();
        HashMap<String, Boolean> receivers3 = new HashMap<>();
        HashMap<String, Boolean> providers3 = new HashMap<>();
        HashMap<String, String> remoteFragments3 = new HashMap<>();
        HashMap<String, String> remoteViews3 = new HashMap<>();
        HashMap<String, String> remoteTransactors3 = new HashMap<>();
        List<String> dependencies3 = new ArrayList<>();
        info3.activities = activities3;
        info3.services = services3;
        info3.receivers = receivers3;
        info3.contentProviders = providers3;
        info3.remoteFragments = remoteFragments3;
        info3.remoteViews = remoteViews3;
        info3.remoteTransactors = remoteTransactors3;
        info3.dependency = dependencies3;
        info3.unique_tag = "mwjqnpu15x28";
        info3.pkgName = "com.yunos.tvtaobao.search";
        info3.isInternal = true;
        activities3.put("com.yunos.tvtaobao.search.activity.SearchActivity", Boolean.FALSE);
        activities3.put(BaseConfig.SWITCH_TO_SEARCH_ACTIVITY, Boolean.FALSE);
        activities3.put("com.yunos.tvtaobao.search.activity.SearchResultActivity", Boolean.FALSE);
        bundleInfos.put(info3.pkgName, info3);
        BundleListing.BundleInfo info4 = new BundleListing.BundleInfo();
        HashMap<String, Boolean> activities4 = new HashMap<>();
        HashMap<String, Boolean> services4 = new HashMap<>();
        HashMap<String, Boolean> receivers4 = new HashMap<>();
        HashMap<String, Boolean> providers4 = new HashMap<>();
        HashMap<String, String> remoteFragments4 = new HashMap<>();
        HashMap<String, String> remoteViews4 = new HashMap<>();
        HashMap<String, String> remoteTransactors4 = new HashMap<>();
        List<String> dependencies4 = new ArrayList<>();
        info4.activities = activities4;
        info4.services = services4;
        info4.receivers = receivers4;
        info4.contentProviders = providers4;
        info4.remoteFragments = remoteFragments4;
        info4.remoteViews = remoteViews4;
        info4.remoteTransactors = remoteTransactors4;
        info4.dependency = dependencies4;
        info4.unique_tag = "3rab4y48cyv0t";
        info4.pkgName = "com.yunos.tvtaobao.newcart";
        info4.isInternal = true;
        activities4.put(BaseConfig.SWITCH_TO_GUESS_YOU_LIKE_ACTIVITY, Boolean.FALSE);
        activities4.put(BaseConfig.SWITCH_TO_SHOPCART_LIST_ACTIVITY, Boolean.FALSE);
        activities4.put(BaseConfig.SWITCH_TO_FIND_SAME_ACTIVITY, Boolean.FALSE);
        activities4.put("com.yunos.tvtaobao.payresult.PayResultBuyRebateActivity", Boolean.FALSE);
        activities4.put("com.yunos.tvtaobao.newcart.ui.activity.CouponActivity", Boolean.FALSE);
        activities4.put(BaseConfig.SWITCH_TO_LOGINOUT_ACTIVITY, Boolean.FALSE);
        activities4.put(BaseConfig.SWITCH_TO_PAYRESULT_ACTIVITY, Boolean.FALSE);
        activities4.put("com.yunos.tvtaobao.newsku.TvTaoSkuActivity", Boolean.FALSE);
        activities4.put(BaseConfig.SWITCH_TO_ERROR_PAGE_ACTIVITY, Boolean.FALSE);
        bundleInfos.put(info4.pkgName, info4);
        BundleListing.BundleInfo info5 = new BundleListing.BundleInfo();
        HashMap<String, Boolean> activities5 = new HashMap<>();
        HashMap<String, Boolean> services5 = new HashMap<>();
        HashMap<String, Boolean> receivers5 = new HashMap<>();
        HashMap<String, Boolean> providers5 = new HashMap<>();
        HashMap<String, String> remoteFragments5 = new HashMap<>();
        HashMap<String, String> remoteViews5 = new HashMap<>();
        HashMap<String, String> remoteTransactors5 = new HashMap<>();
        List<String> dependencies5 = new ArrayList<>();
        info5.activities = activities5;
        info5.services = services5;
        info5.receivers = receivers5;
        info5.contentProviders = providers5;
        info5.remoteFragments = remoteFragments5;
        info5.remoteViews = remoteViews5;
        info5.remoteTransactors = remoteTransactors5;
        info5.dependency = dependencies5;
        info5.unique_tag = "3h6bvb46uq51d";
        info5.pkgName = "com.yunos.tvtaobao.tvshoppingbundle";
        info5.isInternal = true;
        services5.put("com.yunos.tvtaobao.tvshoppingbundle.service.TvShopService", Boolean.FALSE);
        receivers5.put("com.yunos.tvtaobao.tvshoppingbundle.broadcast.TvShopBootBroadcast", Boolean.FALSE);
        receivers5.put("com.yunos.tvtaobao.tvshoppingbundle.broadcast.SmileRecognitionBroadcast", Boolean.FALSE);
        bundleInfos.put(info5.pkgName, info5);
        BundleListing.BundleInfo info6 = new BundleListing.BundleInfo();
        HashMap<String, Boolean> activities6 = new HashMap<>();
        HashMap<String, Boolean> services6 = new HashMap<>();
        HashMap<String, Boolean> receivers6 = new HashMap<>();
        HashMap<String, Boolean> providers6 = new HashMap<>();
        HashMap<String, String> remoteFragments6 = new HashMap<>();
        HashMap<String, String> remoteViews6 = new HashMap<>();
        HashMap<String, String> remoteTransactors6 = new HashMap<>();
        List<String> dependencies6 = new ArrayList<>();
        info6.activities = activities6;
        info6.services = services6;
        info6.receivers = receivers6;
        info6.contentProviders = providers6;
        info6.remoteFragments = remoteFragments6;
        info6.remoteViews = remoteViews6;
        info6.remoteTransactors = remoteTransactors6;
        info6.dependency = dependencies6;
        info6.unique_tag = "2rni6wnpwp9nb";
        info6.pkgName = "com.yunos.tvtaobao.zhuanti";
        info6.isInternal = true;
        activities6.put(BaseConfig.SWITCH_TO_DAREN_ACTIVITY, Boolean.FALSE);
        activities6.put(BaseConfig.SWITCH_TO_DARENTV_ACTIVITY, Boolean.FALSE);
        activities6.put(BaseConfig.SWITCH_TO_NEW_TVBUY_ACTIVITY, Boolean.FALSE);
        activities6.put(BaseConfig.SWITCH_TO_TVBUY_ACTIVITY, Boolean.FALSE);
        activities6.put(BaseConfig.SWITCH_TO_TAOBAOTV_ACTIVITY, Boolean.FALSE);
        bundleInfos.put(info6.pkgName, info6);
        BundleListing.BundleInfo info7 = new BundleListing.BundleInfo();
        HashMap<String, Boolean> activities7 = new HashMap<>();
        HashMap<String, Boolean> services7 = new HashMap<>();
        HashMap<String, Boolean> receivers7 = new HashMap<>();
        HashMap<String, Boolean> providers7 = new HashMap<>();
        HashMap<String, String> remoteFragments7 = new HashMap<>();
        HashMap<String, String> remoteViews7 = new HashMap<>();
        HashMap<String, String> remoteTransactors7 = new HashMap<>();
        List<String> dependencies7 = new ArrayList<>();
        info7.activities = activities7;
        info7.services = services7;
        info7.receivers = receivers7;
        info7.contentProviders = providers7;
        info7.remoteFragments = remoteFragments7;
        info7.remoteViews = remoteViews7;
        info7.remoteTransactors = remoteTransactors7;
        info7.dependency = dependencies7;
        info7.unique_tag = "1n4wvb65t1igq";
        info7.pkgName = "com.tvtaobao.android.games";
        info7.isInternal = true;
        activities7.put(BaseConfig.SWITCH_TO_GAMES, Boolean.FALSE);
        bundleInfos.put(info7.pkgName, info7);
        BundleListing.BundleInfo info8 = new BundleListing.BundleInfo();
        HashMap<String, Boolean> activities8 = new HashMap<>();
        HashMap<String, Boolean> services8 = new HashMap<>();
        HashMap<String, Boolean> receivers8 = new HashMap<>();
        HashMap<String, Boolean> providers8 = new HashMap<>();
        HashMap<String, String> remoteFragments8 = new HashMap<>();
        HashMap<String, String> remoteViews8 = new HashMap<>();
        HashMap<String, String> remoteTransactors8 = new HashMap<>();
        List<String> dependencies8 = new ArrayList<>();
        info8.activities = activities8;
        info8.services = services8;
        info8.receivers = receivers8;
        info8.contentProviders = providers8;
        info8.remoteFragments = remoteFragments8;
        info8.remoteViews = remoteViews8;
        info8.remoteTransactors = remoteTransactors8;
        info8.dependency = dependencies8;
        info8.unique_tag = "2fty0p9366csa";
        info8.pkgName = "com.yunos.tvtaobao.flashsale";
        info8.isInternal = true;
        activities8.put(BaseConfig.SWITCH_TO_FLASHSALE_MAIN_ACTIVITY, Boolean.FALSE);
        activities8.put("com.yunos.tvtaobao.flashsale.activity.RecommendActivity", Boolean.FALSE);
        bundleInfos.put(info8.pkgName, info8);
        BundleListing.BundleInfo info9 = new BundleListing.BundleInfo();
        HashMap<String, Boolean> activities9 = new HashMap<>();
        HashMap<String, Boolean> services9 = new HashMap<>();
        HashMap<String, Boolean> receivers9 = new HashMap<>();
        HashMap<String, Boolean> providers9 = new HashMap<>();
        HashMap<String, String> remoteFragments9 = new HashMap<>();
        HashMap<String, String> remoteViews9 = new HashMap<>();
        HashMap<String, String> remoteTransactors9 = new HashMap<>();
        List<String> dependencies9 = new ArrayList<>();
        info9.activities = activities9;
        info9.services = services9;
        info9.receivers = receivers9;
        info9.contentProviders = providers9;
        info9.remoteFragments = remoteFragments9;
        info9.remoteViews = remoteViews9;
        info9.remoteTransactors = remoteTransactors9;
        info9.dependency = dependencies9;
        info9.unique_tag = "2xtjvhm08hfb8";
        info9.pkgName = "com.yunos.tvtaobao.juhuasuan";
        info9.isInternal = true;
        activities9.put(BaseConfig.SWITCH_TO_JUHUASUAN_ACTIVITY, Boolean.FALSE);
        activities9.put(BaseConfig.SWITCH_TO_JHS_ACTIVITY, Boolean.FALSE);
        activities9.put("com.yunos.tvtaobao.juhuasuan.activity.HomeCategoryActivity", Boolean.FALSE);
        activities9.put("com.yunos.tvtaobao.juhuasuan.activity.HomeActivity", Boolean.FALSE);
        activities9.put("com.yunos.tvtaobao.juhuasuan.activity.BrandHomeActivity", Boolean.FALSE);
        activities9.put("com.yunos.tvtaobao.juhuasuan.activity.BrandDetailActivity", Boolean.FALSE);
        bundleInfos.put(info9.pkgName, info9);
        BundleListing.BundleInfo info10 = new BundleListing.BundleInfo();
        HashMap<String, Boolean> activities10 = new HashMap<>();
        HashMap<String, Boolean> services10 = new HashMap<>();
        HashMap<String, Boolean> receivers10 = new HashMap<>();
        HashMap<String, Boolean> providers10 = new HashMap<>();
        HashMap<String, String> remoteFragments10 = new HashMap<>();
        HashMap<String, String> remoteViews10 = new HashMap<>();
        HashMap<String, String> remoteTransactors10 = new HashMap<>();
        List<String> dependencies10 = new ArrayList<>();
        info10.activities = activities10;
        info10.services = services10;
        info10.receivers = receivers10;
        info10.contentProviders = providers10;
        info10.remoteFragments = remoteFragments10;
        info10.remoteViews = remoteViews10;
        info10.remoteTransactors = remoteTransactors10;
        info10.dependency = dependencies10;
        info10.unique_tag = "2k3mhcc7pmsdo";
        info10.pkgName = "com.yunos.tvtaobao.menu";
        info10.isInternal = true;
        activities10.put(BaseConfig.SWITCH_TO_MENU_ACTIVITY, Boolean.FALSE);
        bundleInfos.put(info10.pkgName, info10);
        BundleListing.BundleInfo info11 = new BundleListing.BundleInfo();
        HashMap<String, Boolean> activities11 = new HashMap<>();
        HashMap<String, Boolean> services11 = new HashMap<>();
        HashMap<String, Boolean> receivers11 = new HashMap<>();
        HashMap<String, Boolean> providers11 = new HashMap<>();
        HashMap<String, String> remoteFragments11 = new HashMap<>();
        HashMap<String, String> remoteViews11 = new HashMap<>();
        HashMap<String, String> remoteTransactors11 = new HashMap<>();
        List<String> dependencies11 = new ArrayList<>();
        info11.activities = activities11;
        info11.services = services11;
        info11.receivers = receivers11;
        info11.contentProviders = providers11;
        info11.remoteFragments = remoteFragments11;
        info11.remoteViews = remoteViews11;
        info11.remoteTransactors = remoteTransactors11;
        info11.dependency = dependencies11;
        info11.unique_tag = "2wj0izygxvuht";
        info11.pkgName = "com.yunos.tvtaobao.goodlist";
        info11.isInternal = true;
        activities11.put(BaseConfig.SWITCH_TO_GOODLIST_ACTIVITY, Boolean.FALSE);
        activities11.put(BaseConfig.SWITCH_TO_SHOP_ACTIVITY, Boolean.FALSE);
        bundleInfos.put(info11.pkgName, info11);
        BundleListing.BundleInfo info12 = new BundleListing.BundleInfo();
        HashMap<String, Boolean> activities12 = new HashMap<>();
        HashMap<String, Boolean> services12 = new HashMap<>();
        HashMap<String, Boolean> receivers12 = new HashMap<>();
        HashMap<String, Boolean> providers12 = new HashMap<>();
        HashMap<String, String> remoteFragments12 = new HashMap<>();
        HashMap<String, String> remoteViews12 = new HashMap<>();
        HashMap<String, String> remoteTransactors12 = new HashMap<>();
        List<String> dependencies12 = new ArrayList<>();
        info12.activities = activities12;
        info12.services = services12;
        info12.receivers = receivers12;
        info12.contentProviders = providers12;
        info12.remoteFragments = remoteFragments12;
        info12.remoteViews = remoteViews12;
        info12.remoteTransactors = remoteTransactors12;
        info12.dependency = dependencies12;
        info12.unique_tag = "3a0j31e1z6ixm";
        info12.pkgName = "com.yunos.tvtaobao.answer";
        info12.isInternal = true;
        activities12.put(BaseConfig.SWITCH_TO_ANSWER_ACTIVITY, Boolean.FALSE);
        activities12.put(BaseConfig.SWITCH_TO_HQLIVE_ACTIVITY, Boolean.FALSE);
        bundleInfos.put(info12.pkgName, info12);
        BundleListing.BundleInfo info13 = new BundleListing.BundleInfo();
        HashMap<String, Boolean> activities13 = new HashMap<>();
        HashMap<String, Boolean> services13 = new HashMap<>();
        HashMap<String, Boolean> receivers13 = new HashMap<>();
        HashMap<String, Boolean> providers13 = new HashMap<>();
        HashMap<String, String> remoteFragments13 = new HashMap<>();
        HashMap<String, String> remoteViews13 = new HashMap<>();
        HashMap<String, String> remoteTransactors13 = new HashMap<>();
        List<String> dependencies13 = new ArrayList<>();
        info13.activities = activities13;
        info13.services = services13;
        info13.receivers = receivers13;
        info13.contentProviders = providers13;
        info13.remoteFragments = remoteFragments13;
        info13.remoteViews = remoteViews13;
        info13.remoteTransactors = remoteTransactors13;
        info13.dependency = dependencies13;
        info13.unique_tag = "11h4ii0005ajz";
        info13.pkgName = "com.yunos.tvtaobao.takeoutbundle";
        info13.isInternal = true;
        activities13.put(BaseConfig.SWITCH_TO_TAKEOUT_SHOP_HOME, Boolean.FALSE);
        activities13.put(BaseConfig.SWITCH_TO_TAKEOUT_ORDER_DETAIL_ACTIVITY, Boolean.FALSE);
        activities13.put(BaseConfig.SWITCH_TO_TAKEOUT_ORDER_LIST_ACTIVITY, Boolean.FALSE);
        activities13.put(BaseConfig.SWITCH_TO_TAKEOUT_HOME_TEST, Boolean.FALSE);
        activities13.put(BaseConfig.SWITCH_TO_TEST_SEARCH, Boolean.FALSE);
        activities13.put("com.yunos.tvtaobao.takeoutbundle.activity.TakeOutCouponActivity", Boolean.FALSE);
        activities13.put(BaseConfig.SWITCH_TO_TAKEOUT_MINE, Boolean.FALSE);
        activities13.put("com.yunos.tvtaobao.takeoutbundle.activity.TakeOutCreateOrderActivity", Boolean.FALSE);
        activities13.put(BaseConfig.SWITCH_TO_ELEM_BIND_GUILD, Boolean.FALSE);
        activities13.put("com.yunos.tvtaobao.elem.activity.bind.ElemAuthActivity", Boolean.FALSE);
        activities13.put("com.yunos.tvtaobao.elem.activity.bind.ElemBindActivity", Boolean.FALSE);
        activities13.put("com.yunos.tvtaobao.elem.activity.bind.ElemBindAgreementActivity", Boolean.FALSE);
        activities13.put("com.yunos.tvtaobao.elem.activity.bind.ElemRegisterAndBindActivity", Boolean.FALSE);
        activities13.put("com.yunos.tvtaobao.elem.activity.bind.ElemRegisterAndBindAgreementActivity", Boolean.FALSE);
        bundleInfos.put(info13.pkgName, info13);
        BundleListing.BundleInfo info14 = new BundleListing.BundleInfo();
        HashMap<String, Boolean> activities14 = new HashMap<>();
        HashMap<String, Boolean> services14 = new HashMap<>();
        HashMap<String, Boolean> receivers14 = new HashMap<>();
        HashMap<String, Boolean> providers14 = new HashMap<>();
        HashMap<String, String> remoteFragments14 = new HashMap<>();
        HashMap<String, String> remoteViews14 = new HashMap<>();
        HashMap<String, String> remoteTransactors14 = new HashMap<>();
        List<String> dependencies14 = new ArrayList<>();
        info14.activities = activities14;
        info14.services = services14;
        info14.receivers = receivers14;
        info14.contentProviders = providers14;
        info14.remoteFragments = remoteFragments14;
        info14.remoteViews = remoteViews14;
        info14.remoteTransactors = remoteTransactors14;
        info14.dependency = dependencies14;
        info14.unique_tag = "3dxkxfxmpkv17";
        info14.pkgName = "com.yunos.tvtaobao.live";
        info14.isInternal = true;
        activities14.put("com.yunos.tvtaobao.live.activity.MainActivity", Boolean.FALSE);
        activities14.put("com.yunos.tvtaobao.live.activity.TMallLiveActivity", Boolean.FALSE);
        activities14.put(BaseConfig.SWITCH_TO_TABPBAO_LIVE_ACTIVITY, Boolean.FALSE);
        activities14.put("com.yunos.tvtaobao.live.activity.TestLiveActivity", Boolean.FALSE);
        bundleInfos.put(info14.pkgName, info14);
        BundleListing.BundleInfo info15 = new BundleListing.BundleInfo();
        HashMap<String, Boolean> activities15 = new HashMap<>();
        HashMap<String, Boolean> services15 = new HashMap<>();
        HashMap<String, Boolean> receivers15 = new HashMap<>();
        HashMap<String, Boolean> providers15 = new HashMap<>();
        HashMap<String, String> remoteFragments15 = new HashMap<>();
        HashMap<String, String> remoteViews15 = new HashMap<>();
        HashMap<String, String> remoteTransactors15 = new HashMap<>();
        List<String> dependencies15 = new ArrayList<>();
        info15.activities = activities15;
        info15.services = services15;
        info15.receivers = receivers15;
        info15.contentProviders = providers15;
        info15.remoteFragments = remoteFragments15;
        info15.remoteViews = remoteViews15;
        info15.remoteTransactors = remoteTransactors15;
        info15.dependency = dependencies15;
        info15.unique_tag = "31von6pgxms25";
        info15.pkgName = "com.yunos.voice";
        info15.isInternal = true;
        activities15.put("com.yunos.voice.activity.MainActivity", Boolean.FALSE);
        activities15.put(BaseConfig.SWITCH_TO_VOICE_CREATE_ORDER_ACTIVITY, Boolean.FALSE);
        activities15.put("com.yunos.voice.activity.GoodsSearchActivity", Boolean.FALSE);
        activities15.put("com.yunos.voice.activity.VoiceVideoDemoActivity", Boolean.FALSE);
        activities15.put("com.yunos.voice.activity.LoginAuthActivity", Boolean.FALSE);
        activities15.put("com.yunos.voice.activity.NoviceGuideActivity", Boolean.FALSE);
        activities15.put("com.yunos.voice.activity.BillQueryActivity", Boolean.FALSE);
        activities15.put("com.yunos.voice.activity.LogisticsQueryActivity", Boolean.FALSE);
        activities15.put("com.yunos.voice.activity.OrderDeliveryActivity", Boolean.FALSE);
        activities15.put("com.yunos.voice.activity.FusionSearchActivity", Boolean.FALSE);
        activities15.put("com.yunos.voice.activity.TakeOutSearchActivity", Boolean.FALSE);
        bundleInfos.put(info15.pkgName, info15);
        BundleListing.BundleInfo info16 = new BundleListing.BundleInfo();
        HashMap<String, Boolean> activities16 = new HashMap<>();
        HashMap<String, Boolean> services16 = new HashMap<>();
        HashMap<String, Boolean> receivers16 = new HashMap<>();
        HashMap<String, Boolean> providers16 = new HashMap<>();
        HashMap<String, String> remoteFragments16 = new HashMap<>();
        HashMap<String, String> remoteViews16 = new HashMap<>();
        HashMap<String, String> remoteTransactors16 = new HashMap<>();
        List<String> dependencies16 = new ArrayList<>();
        info16.activities = activities16;
        info16.services = services16;
        info16.receivers = receivers16;
        info16.contentProviders = providers16;
        info16.remoteFragments = remoteFragments16;
        info16.remoteViews = remoteViews16;
        info16.remoteTransactors = remoteTransactors16;
        info16.dependency = dependencies16;
        info16.unique_tag = "1wvad2ew5wpfl";
        info16.pkgName = "com.yunos.tvtaobao.tradelink";
        info16.isInternal = true;
        activities16.put(BaseConfig.SWITCH_TO_ADDRESSEDIT_ACTIVITY, Boolean.FALSE);
        activities16.put(BaseConfig.SWITCH_TO_BUILDORDER_ACTIVITY, Boolean.FALSE);
        activities16.put(BaseConfig.SWITCH_TO_NEWBUILDORDER_ACTIVITY, Boolean.FALSE);
        activities16.put("com.yunos.tvtaobao.tradelink.activity.CreateOrderActivity", Boolean.FALSE);
        bundleInfos.put(info16.pkgName, info16);
        BundleListing.BundleInfo info17 = new BundleListing.BundleInfo();
        HashMap<String, Boolean> activities17 = new HashMap<>();
        HashMap<String, Boolean> services17 = new HashMap<>();
        HashMap<String, Boolean> receivers17 = new HashMap<>();
        HashMap<String, Boolean> providers17 = new HashMap<>();
        HashMap<String, String> remoteFragments17 = new HashMap<>();
        HashMap<String, String> remoteViews17 = new HashMap<>();
        HashMap<String, String> remoteTransactors17 = new HashMap<>();
        List<String> dependencies17 = new ArrayList<>();
        info17.activities = activities17;
        info17.services = services17;
        info17.receivers = receivers17;
        info17.contentProviders = providers17;
        info17.remoteFragments = remoteFragments17;
        info17.remoteViews = remoteViews17;
        info17.remoteTransactors = remoteTransactors17;
        info17.dependency = dependencies17;
        info17.unique_tag = "tvyb31yo9mdb";
        info17.pkgName = "com.yunos.tvtaobao.detailbundle";
        info17.isInternal = true;
        activities17.put("com.yunos.tvtaobao.detailbundle.activity.DetailEvaluateActivity", Boolean.FALSE);
        activities17.put(BaseConfig.SWITCH_TO_SKILL_GRAPHICDETAILS_ACTIVITY, Boolean.FALSE);
        activities17.put(BaseConfig.SWITCH_TO_DETAIL_ACTIVITY, Boolean.FALSE);
        activities17.put("com.yunos.tvtaobao.detailbundle.activity.CouponActivity", Boolean.FALSE);
        activities17.put("com.yunos.tvtaobao.detailbundle.activity.ShareActivity", Boolean.FALSE);
        activities17.put("com.yunos.tvtaobao.detailbundle.activity.HaierShareActivity", Boolean.FALSE);
        bundleInfos.put(info17.pkgName, info17);
        return listing;
    }
}
